version: "3.2"
services:
    api:
        build: .
        networks:
            - yelpnet
        ports:
            - "8000:8000"
        environment:
            MYSQL_HOST: "assignment2-mysql_db_1"
            MYSQL_DATABASE: "miniYelp"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
        depends_on:
            - db
    db:
        image: mysql
        volumes: 
            - type: volume
              source: yelp-volume
              target: /var/lib/mysql
            - type: bind
              source: ./sql_script
              target: /docker-entrypoint-initdb.d
        networks:
            - yelpnet
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "miniYelp"
            MYSQL_HOST: "localhost"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
        expose:
            - "3306"

volumes:
    yelp-volume:
        external: false

networks:
    yelpnet:
        driver: bridge