#!/bin/bash

#Builds api server using Dockerfile
docker build -f Dockerfile -t a4-api-server .

#Builds consumer server using Dockerfile-resizer
#docker build -f Dockerfile-resizer -t a4-consumer .

docker run -d --name api-server --network assignment4_default -p 8000:8000 -e "MONGO_DATABASE=businesses" -e "MONGO_USER=businesses" -e "MONGO_PASSWORD=hunter2" -e "MONGO_HOST=assignment4_mongodb_1" -e "MONGO_PORT=27017" -e "RABBITMQ_HOST=assignment4_rabbitmq_1" a4-api-server
#docker run -d --name consumer-server --network assignment4_default -e "MONGO_DATABASE=businesses" -e "MONGO_USER=businesses" -e "MONGO_PASSWORD=hunter2" -e "MONGO_HOST=assignment4_mongodb_1" -e "MONGO_PORT=27017" -e "RABBITMQ_HOST=assignment4_rabbitmq_1" a4-consumer