#!/bin/bash

docker run -d --name mysql-server --network mysql-net -p "3306:3306" -e "MYSQL_RANDOM_ROOT_PASSWORD=yes" -e "MYSQL_DATABASE=lodgings" -e "MYSQL_USER=lodgings" -e "MYSQL_PASSWORD=noodle" mysql
