version: "3.2"
services:
    api:
        build: .
        restart: always
        networks:
            - yelpnet
        ports:
            - "8000:8000"
        environment:
            MONGO_HOST: "assignment2-mongo_db_1"
            MONGO_DATABASE: "miniYelp"
            MONGO_USER: "test"
            MONGO_PASSWORD: "test"
        depends_on:
            - db
    db:
        image: mongo
        restart: always
        volumes: 
            - type: volume
              source: a2mongo-volume
              target: /data/db/
            - type: bind
              source: ./mongo_script
              target: /docker-entrypoint-initdb.d
        networks:
            - yelpnet
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: miniYelp
        expose:
            - "27017"

volumes:
    a2mongo-volume:
        external: false

networks:
    yelpnet:
        driver: bridge