#!/bin/bash

docker run -d --name mongo-server --network mongo-net -p "27017:27017" -e "MONGO_INITDB_ROOT_USERNAME=root" -e "MONGO_INITDB_ROOT_PASSWORD=test1" mongo:latest
#Need to wait for server to launch
docker run --rm -it --network mongo-net mongo:latest mongo --host mongo-server --username root --password test1 --authenticationDatabase admin